// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List detected applications running on VMs
	// (GET /applications)
	GetApplications(c *gin.Context)
	// Get cluster-level utilization aggregates for the latest completed report
	// (GET /cluster_rightsizing)
	GetLatestRightsizingClusters(c *gin.Context, params GetLatestRightsizingClustersParams)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /cluster_rightsizing/{report_id})
	GetRightsizingReportClusters(c *gin.Context, reportId string, params GetRightsizingReportClustersParams)
	// Get latest cluster utilization by cluster ID
	// (GET /clusters/{cluster_id}/utilization)
	GetClusterUtilization(c *gin.Context, clusterId string)
	// Stop collection
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start inventory collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// Verify vCenter credentials and permissions
	// (PUT /forecaster/credentials)
	PutForecasterCredentials(c *gin.Context)
	// List available datastores
	// (POST /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List all groups
	// (GET /groups)
	ListGroups(c *gin.Context, params ListGroupsParams)
	// Create a new group
	// (POST /groups)
	CreateGroup(c *gin.Context)
	// Delete group
	// (DELETE /groups/{id})
	DeleteGroup(c *gin.Context, id string)
	// Get group by ID with its VMs
	// (GET /groups/{id})
	GetGroup(c *gin.Context, id string, params GetGroupParams)
	// Update group
	// (PATCH /groups/{id})
	UpdateGroup(c *gin.Context, id string)
	// Stop inspector entirely
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Validate vCenter credentials for inspector
	// (POST /inspector/credentials)
	ValidateInspectorCredentials(c *gin.Context)
	// Get VDDK status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get collected inventory
	// (GET /inventory)
	GetInventory(c *gin.Context, params GetInventoryParams)
	// List all rightsizing reports
	// (GET /rightsizing)
	ListRightsizingReports(c *gin.Context)
	// Trigger rightsizing metrics collection
	// (POST /rightsizing)
	TriggerRightsizingCollection(c *gin.Context)
	// Get a specific rightsizing report with full VM metrics
	// (GET /rightsizing/{report_id})
	GetRightsizingReport(c *gin.Context, reportId string)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /rightsizing/{report_id}/clusters)
	ListRightsizingReportClusters(c *gin.Context, reportId string, params ListRightsizingReportClustersParams)
	// Get utilization for a specific cluster from a specific report
	// (GET /rightsizing/{report_id}/clusters/{cluster_id})
	GetRightsizingReportCluster(c *gin.Context, reportId string, clusterId string)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// Get list of VMs with filtering and pagination
	// (GET /vms)
	GetVMs(c *gin.Context, params GetVMsParams)
	// Get distinct filter option values for VMs
	// (GET /vms/filter-options)
	GetVMsFilterOptions(c *gin.Context)
	// Get all distinct labels in use across VMs
	// (GET /vms/labels)
	GetVMLabels(c *gin.Context)
	// Delete label from all VMs
	// (DELETE /vms/labels/{label})
	DeleteLabelGlobally(c *gin.Context, label string)
	// Modify label VM membership (add/remove label to/from VMs)
	// (PATCH /vms/labels/{label})
	UpdateLabelVMs(c *gin.Context, label string)
	// Get details about a vm
	// (GET /vms/{id})
	GetVM(c *gin.Context, id string)
	// Update VM properties
	// (PATCH /vms/{id})
	UpdateVM(c *gin.Context, id string)
	// Remove VirtualMachine from inspection queue
	// (DELETE /vms/{id}/inspection)
	RemoveVMFromInspection(c *gin.Context, id string)
	// Get utilization breakdown for a specific VM
	// (GET /vms/{id}/utilization)
	GetVMUtilization(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// GetApplications operation middleware
func (siw *ServerInterfaceWrapper) GetApplications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApplications(c)
}

// GetLatestRightsizingClusters operation middleware
func (siw *ServerInterfaceWrapper) GetLatestRightsizingClusters(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestRightsizingClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestRightsizingClusters(c, params)
}

// GetRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportClusters(c, reportId, params)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, clusterId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// PutForecasterCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutForecasterCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutForecasterCredentials(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, params)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGroup(c)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGroup(c, id)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, params)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGroup(c, id)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// ValidateInspectorCredentials operation middleware
func (siw *ServerInterfaceWrapper) ValidateInspectorCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ValidateInspectorCredentials(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInventoryParams

	// ------------- Optional query parameter "withAgentId" -------------

	err = runtime.BindQueryParameter("form", true, false, "withAgentId", c.Request.URL.Query(), &params.WithAgentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter withAgentId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", c.Request.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter group_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, params)
}

// ListRightsizingReports operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReports(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReports(c)
}

// TriggerRightsizingCollection operation middleware
func (siw *ServerInterfaceWrapper) TriggerRightsizingCollection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TriggerRightsizingCollection(c)
}

// GetRightsizingReport operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReport(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReport(c, reportId)
}

// ListRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReportClusters(c, reportId, params)
}

// GetRightsizingReportCluster operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportCluster(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportCluster(c, reportId, clusterId)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GetVMs operation middleware
func (siw *ServerInterfaceWrapper) GetVMs(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVMsParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMs(c, params)
}

// GetVMsFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMsFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMsFilterOptions(c)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c)
}

// DeleteLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLabelGlobally(c, label)
}

// UpdateLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLabelVMs(c, label)
}

// GetVM operation middleware
func (siw *ServerInterfaceWrapper) GetVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVM(c, id)
}

// UpdateVM operation middleware
func (siw *ServerInterfaceWrapper) UpdateVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateVM(c, id)
}

// RemoveVMFromInspection operation middleware
func (siw *ServerInterfaceWrapper) RemoveVMFromInspection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveVMFromInspection(c, id)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/applications", wrapper.GetApplications)
	router.GET(options.BaseURL+"/cluster_rightsizing", wrapper.GetLatestRightsizingClusters)
	router.GET(options.BaseURL+"/cluster_rightsizing/:report_id", wrapper.GetRightsizingReportClusters)
	router.GET(options.BaseURL+"/clusters/:cluster_id/utilization", wrapper.GetClusterUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.PUT(options.BaseURL+"/forecaster/credentials", wrapper.PutForecasterCredentials)
	router.POST(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateGroup)
	router.DELETE(options.BaseURL+"/groups/:id", wrapper.DeleteGroup)
	router.GET(options.BaseURL+"/groups/:id", wrapper.GetGroup)
	router.PATCH(options.BaseURL+"/groups/:id", wrapper.UpdateGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.POST(options.BaseURL+"/inspector/credentials", wrapper.ValidateInspectorCredentials)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/rightsizing", wrapper.ListRightsizingReports)
	router.POST(options.BaseURL+"/rightsizing", wrapper.TriggerRightsizingCollection)
	router.GET(options.BaseURL+"/rightsizing/:report_id", wrapper.GetRightsizingReport)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters", wrapper.ListRightsizingReportClusters)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters/:cluster_id", wrapper.GetRightsizingReportCluster)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/vms", wrapper.GetVMs)
	router.GET(options.BaseURL+"/vms/filter-options", wrapper.GetVMsFilterOptions)
	router.GET(options.BaseURL+"/vms/labels", wrapper.GetVMLabels)
	router.DELETE(options.BaseURL+"/vms/labels/:label", wrapper.DeleteLabelGlobally)
	router.PATCH(options.BaseURL+"/vms/labels/:label", wrapper.UpdateLabelVMs)
	router.GET(options.BaseURL+"/vms/:id", wrapper.GetVM)
	router.PATCH(options.BaseURL+"/vms/:id", wrapper.UpdateVM)
	router.DELETE(options.BaseURL+"/vms/:id/inspection", wrapper.RemoveVMFromInspection)
	router.GET(options.BaseURL+"/vms/:id/utilization", wrapper.GetVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3PcOJLgX0HU7URLMSWpJD+m7Ql/0MN2K8Zl6/Tqi2j7PCgSVYUVCbABsOSaPkfs",
	"f7iL2B+0/2R/yQUSAAmS4KP0sHt2+8uMWwUCiUQike/8bRTxNOOMMCVHL38byWhJUgz/PFwQpqY8Jufk",
	"15xIpf+WCZ4RoSiBESmPif5/wvJ09PKXUcQZI5Ei8Wg8iqks//PTeKTWGRm9HEklKFuMxqMvOxxndCfi",
	"MVkQtkO+KIF3FF7AxDPKYj3s5UiQX3MqSDzmjPD5q2JKVJn/69ev42KohgQgK1fls38lkRp9HZtNXSis",
	"ctncT8SZ5An5bCemnOm/xkRGgmbmP0fHuRCEKWTHonIskmbacYGPCozjUQc+vo5HRAguAuuV88MI5P8c",
	"mMadSXWWSywWRCH9I5pzgdSSIKxR4UG72enpr3ZWWDCcauT94mNWE82xN1vtp5PK5MGjG4fOInieWZbQ",
	"COvf31GpzonMOJOkeba4HAj/TRVJ4R//Ish89HL0P/bKi7Bnb8GeN/uHFRErSm71ohYKLARej+rwVxbq",
	"AbmYtAFu5fh+ax6zRnvwh1V6zHOmvN8oU2RBhPnxTnu/nvbuGuAZj6rE6WAxC/fg4nraxAKNN9l8DSSq",
	"SQ+GhlY+IixapljcnOcswAkEwYrEh4DHORcpVqOXoxgrsqMo7LQBVEzlzQX9B3k7C+M+zgXs84JE1Ul5",
	"Pku8GVmezswXLRzhNbCBlEiJFwTROVJLKhFVxMyP5pgmcO0aIBp0FitTpp4/Lcd5sBaThbeSErXkcROy",
	"AqfIjEC5JDHaIruL3TFapZ8ZVnRFtkOgZZiK9200nQmSnVTRV2NvNCVIZpovc6afhhsEJ6jRgVmMBGYx",
	"T9GcJgnaKjG1jzhL1hqeAachiZSUs9OhOJQ8FxE5wQpLxUV4YwrYcs+YpeD5YpnlajrL5CDSCV2EEnwP",
	"2U0omzD51FCh8ipJNwAde5codAGPk1wqIt4QrHJBAq9xLORrhmealuHA5zhP1OjlHCeSjGsE8POSqCUR",
	"6OT8Am2dUI29Wa7FhHNidoguoiWJ84SIbUQlImZi+xZSiSIDTYnLGecJwQxuroBnqwLF6D1ndYb3cqSX",
	"x7niqaGvynNbruAe3Dd5kqzRoRkPN/YMC0Vx/a9TzHKcjMZmzZDsoE8KL8jJHTB2YT4FzG2GmK/th3ql",
	"aEL/UXCQhpQ1pzFhUUBO0WSHIr4iAFM5EmVERIQp/detyc7+ZLI9RhFOojzRSEJYotXx2dXOLaGLpf6D",
	"myN4t1P8hab6DPYnk/Eopcz81yRw66Ms/4xXiyakhxbG47MrlJfbDQD6ECCk+EsThKmZ4xuBkL141gTh",
	"xTO1dOvR5FtgIyVp94GkJOVi/Q2g6DyTbwbFoGP5BtDU3hx3b0raKQm5PMRyCyVKxz6DCD4cPElIpLi4",
	"UFgoTznFSfJhPnr5S7dce623TcSxILHGDk7k6Oun2rRB7XCQOHa7JE4RBHYK3wQ5tlvEvQaC4HhdaolG",
	"z4oMUOY/Mixk5c/wOpglhulotT2a/z23Cwd/PPahaRnhgRgccVbA3TUBbCY44LXZYZ3ELAqDJAKSx1vB",
	"86zVeFHTsKqH+gH+gRO00HPUdO4Uf3lH2EItRy+fTSZ3Nm3wVOthmVqPU/zl1bPJBC7RnCb6uW1A9Ab+",
	"jsiXTBhJDm3danF2RtAKJ1SrJvF2Fbj9ycFTc2mLv9zfDpNS9mofIIbpAWanj1UhfmtQR2WW4DWyCmIF",
	"vEcFbtK0ClkYLIpDhFMRxWv0QuXNaVgfnQtCjnGGI6rWb4/COtMSi/gWC3IYRSTR8jSJp3zli/yexLnk",
	"Up0GFKxTYFlzSgTic5Aq9UjNdAQx4lrsNqC5D1YKa7FX68F5kmjJbvRSiZy02I2SFu2LKx7x5BJ+CGko",
	"XOGkb/+q7esVYbHhq93qPPzaXKyB/WLGsTuyduTXNuew0EkZJ0RhmgTEWpzhGU1okL+MTpnelaQR4vN5",
	"wnGM/PHmNCvHN8Nad+YMmd0gmWcZF8qoY6msml2z9Y6dVl8a/d+j8UjEqUbGiidBnaFqzhkD/IDC2UDz",
	"hMb74MEM4xOyolEIN+8PD1EMPyJaELgsFKcCJz9INMPRDWUL9O7qvfRR0bu7VnuZVZ0O9cDQlTshgq60",
	"QiR4ijxIT09QJsicftlFFzgFJpxrQQsziaT+Q7ZcSxrhBNkVEMCyiw5nkjAFu3v/5gLMEwnX44p9yt1R",
	"u443bb2ndsB1cZ+qG7k4vjgtiAk+cpaZ968vD8/Oxujs6vz1GJ28PQ5aaNwFbipshmD172jrevrmYqw3",
	"NkbX1zwZow+XP70+D0wYZs32knu0WNBZ56U8w1Q0r6Rmjh1v++uL/0UNA9WrI8VRRhmQ3KwwZCm+i07n",
	"SL/VisRjhM0HEU9TzvQnM66W3tFptiuJkWcKU0CkVfrgoYZfzitJxE5M5pSR2MBWqOOZ3miIOprWptrx",
	"GzNIyWB8jPfYpIK+hL6Zwgfcb28KnjNJiCLv8IwkbxM+0+jssPTP50acbDIaYEea2V5PJVJLrNASx3Di",
	"iZ4bCZLylW879R4wGBHARvExzHeLZXOWFpQUgLrJQ1t/LRVNsSLnmC1Ii+WT2DGGZ6Z0IbCWx9H+5ZHe",
	"rD4p89R5WJoRqY6xDF1pa9WrcYmPo4Nn6dOJ/DgKsgfyJWvBevt8z9OnL9rmu+VicwBfpPsH4QlDxqo3",
	"XJAIS/BMhbyB9MWzd/yWCGd3rUIBP6EZz1mskfzi2Z98e5UmHLECq92A11EvdZVlbUvBTw+0lKOVMyL2",
	"L4/6nEBV6vsK8vtgM7TW6THbaHhMN/uAbjK608cgcZolpMN3JlUck9VdbfC+yd1b6VMHWRJRMEXZqsVG",
	"nhnj5eaGj6+d6+tXtd1XrnehSHyeM9nFaouBpYtKBhnscPuKRiYYWUinjSX8/JevPninnJRZPvlbuX5+",
	"ZUYiLYjGiAt4yHfcs343/9XRWhF5qZWXABPXf0YzPUKLFHkGCkKcA3fTH2PL8La08q+lx8pv+l+AjYoJ",
	"r90zVYBzBQuFeDb8bAEhMZIczbEIQDRswSGuMNhAE5AzIna8476lakkZwt5xiZx5PpWMGKOA2SW2dgSR",
	"M+YsZ5YaC8uZljaZVguHBjqE7of+X3JWrN0+xAOqddB5AW3rkGNvG62DXtv9tc9SbHyoL1ITavjCGxou",
	"rzjKEsxYUJbqYI0DvJGGUMY1BuTD1s1U61bjhnMqggifaB007iNN+UlCEmBCEm1ZLxvaHyOpJwXOuh28",
	"Bvfk1fUQg5pQROUNkvQfWh5Ab4+Ar3k8rQBzst3t8e/k5eWE/kETYThysciz8BqAscHxJ1Xdzjz2p+bD",
	"/Z5gFLNQLxkE37UCyBY+lAm+EETKkhdzlqzNu2TZzLZvmejaYvClDRgvWnjjBRErGpGdhKxIYhjkLvqg",
	"oVG33Py3ROQLlQr957/9PwQOBrRF44Rs60fNQou2vFNlxf62d9HPek8+q51TRuWSSP01lcjxzTE8oNJA",
	"gwRRuWDwkMGKux53dj4Ox483Zbg+k7RThX9084d8BmEVE6zVPYFATdVLKpxm5vA1Doy3QOuA9ruKTN4Z",
	"PXRnb0TTGj3cg5DdLPbMcHRy8U7TLfkC0uno5cj6DD/mk8kT8gr9+PYIbFU2HgC9Qj9kgsc/tMcZ1XQY",
	"Rn/NHYZKMx/auro6PdkebhsJehUa3+ZZfKdjS7CWC83HA8+uNeqs09EA2+iOWASohvNLQ8AB7pHhkOHA",
	"xbHqX5FVWsJMe1FqRaEnnxWvgx4aFu1Vl9xbTmB33CsxlONgXrtFH9ZWlPegezCSKVsRprhY931xWgz8",
	"pzqK66lEKVbRUr8QxR35QSJL0+N7RpdeU6FynEyxXoH0hpeawzFLbHrsWtB7T9QtFzchL7B+tAIyD06J",
	"87Ex83Hho2CSxsQgRc+NPlwEmWAW8AKdIRzHID5gKemCkVi/kyaAUwt8cxwF+VmKA1GP08NjbzokCWFo",
	"tu4FjJW4qO3Z7hMszmDHzLjQivuASY0vxLly22Y2o1ACw9CWzGeMKJRiCaLH8enJOWJcgVxZ12WfHIT5",
	"QuO8f6JS8YXAqQEj0+IB2CWN47N2/FjhCs22OS5LdppSdo2TnLRZiUgW+qUe5O4msV+MDSQh+v2JB/WU",
	"LD/mgnRK68dnVyiCQa3+X187yfILHt0Q1TuntMOGzNohCnhCQOHeAJNNiP5BGJkeNSfT6HHxTZSh6VHI",
	"JNEPZ7v7e6h/uvA6t/uQT9lc4MBZGpFKnhmLn1H9NqTKKMs/rIg45mlKVUpCb4Q+Oj0mKsagc33VdtFx",
	"JZASuCs6TBIOFwcCKyXaQ+aJOHNuzWNLWQMMr6V7bHPtL7RZTSVn/NaI/NbpE8fUCMlnFdy2Yq48FT3b",
	"cMDgOrbApE/QRsCGmc8mbAZIuu9Mzw+njvjvcrT2U3e29j/xClNzXQadrn1PhqPQPcaBXZvoDnsfwjhs",
	"EWnKm9OGYD3qJ3fWQenlwY6vHrpSLt0kXg+BlZsSZiAy64xRbLEUFN8hZz27n0Zeg6OikAd/K/Tx8WgV",
	"xzcbRGvG8Y13o79uoNGf+iJ6mON2cY5BQr2muob6PpriDDwfVlUGtBk5j1CBCtXBOWYbkK/KJ2AjKOx3",
	"n0OP7umJE2dXx2b2wDPrJlgRIYOWiGvzQ20qhDO6i95wgaz5AH0c/bg72X2yO/k46tWYPajH5cl0nuiJ",
	"FduCp+pnlHShr56A8rVYvZa+MGAS/wvQDu1D3318etDw476251ZqWp2jp7KJadCeDHAh/E5N5ABnp1Lm",
	"ocgKKYmU7iVqUE/U7jxtSeQrYiq6KcQMG/vru9VC22hX9lbylqpouVlGpQt8cixTKsxiLGyarMs00v/l",
	"ph+Pcmbj9VqSfVcJZi3BpKtUtnqhwyGRrTmOZ5iKYxdmuN40ZPENwZLOElJELJqkPllK68Zds2N8NC40",
	"6ZHCE7ud9w+Sa3c/v1QFmf2n8Vge/d+Fm+WcLpZK0n9QtrAMstvU6b/Hg6BuLlDjwHXyMbaM4Mt4uSTW",
	"1IFOT8owXLAH48VCkAXIynPB0963rFym5ylrbqAXO/fGyffDwUAUdKcNmjFB8FcXGYTAT/k5mTvhxE56",
	"zNMs1+KpTQSFaDH0cRTzFFO2E+0fPPk42g5GZ7olw56IE88H4dZ0Il/NeubkJLd2JnicQ1GDHftFKwgd",
	"yZIXV9Mto5z/x797AWF/2kZ7qPhte7eWGRlXUiy3Jv/5b/93fzJBf9reRacayEwQVckUi3CuKM+l83Im",
	"/Hb3IxsY2NaWPlmF3YyqAQ5OywJs3JJvufWn7eGgBFP2fnZLyDxNsViD/ZyInespSvEXE9gt0ZYkBNlc",
	"NsR4Ldime9lgjl4FAyvIgmucXAdoGgwLmsYT4wphpNVUR4M7tzQmMGzrdkmjJbrleRIje1ORoinZwYmx",
	"QZuQNLk9+FxjKm/CW8oEX1GtI5D4b0d6a3posbHKry0nDOn7dzri1tzQ2tJTAMyODsE2bYMtkEi5EXQb",
	"E6BZ7wHosDVXtH91j9TuujpYQD57GP4cZXlA5rzIU73+ypiuc6YkwpHgUiKcJOCUshH6jbT0uqWnspgm",
	"qc83s9b1vLGG/LY0dfatfKd9G5x+TocBc344RVvTAbCE7Fmfo7CzsBoGf0vVskLQ8EDAAqH0/zZdxHue",
	"aw+nB8r4XnnBwHQqT2IrYXVjvotE+iQVk6DaKr3PsIqWnyX9R7VcxPOn485DyIhA/zMnYn1GxBwJnrN4",
	"RwmahePIOiQhIwGZZCQ+R7hNClIcyYhnxNTRWhGxtsKJJxYFozIeIogNFvxsjRjdZSpO5/CojQs4AV0J",
	"XRGTkWUlP0jSgQmKKLTtMcqlcdPqT3Bi4p9A14ndBTKZV4VFzrx/zXxMF2JfoNyC/JeDyWTcIosuqV6K",
	"mvnN51q2pgxJEnEWS7T1ZDJ5FeP1GO3/OJm8uiXkZoz0lK9SztQyHESXcH4zw9HN5yXPhaxDM24kKZjR",
	"6JaymN/q1eG7MlbvLwcT9Ao9maAYr2V4SX2LP/dEFWkUz6wsLPNZYTzuVhV8Yuq5eFOiBI1aUjXs8zww",
	"DyDByt7dIe+mebGHpBeY13XQyBcDRxrB7HM00CBUGT4u0GJgM+uaHRVI6MH6OSgxmyljQ5Qw4D1+lRlb",
	"REDLU5ATj17BW+d06DZWpLXSz3iDKl0uTelzHbMNfZgLApl7yJbAcEJykTFgr9SWu5For7joLTG2IV/4",
	"VWmYNxpjMJakyn8Cj31pQq5xI6t5Xp2/8/MdKigPegLSOxljrqeWYgImGIOvz4TFw4/LfiMVFoMPORSQ",
	"5/AzrsoplekrEFZx3kY3LiDJo8RBF6rbGmboIJRyRqXSxGItNUZgp0TuoitJ0NvXl2hPlEvt/Ubjr3De",
	"8xzERpQCD4X04k0P1sB9YVSEVs9tf1yZfX7dFnvFSm8gLDAIvQ7Mpru8HOmQmBKFjamLqiXPlY+nDrRC",
	"dLMSlKyMiAEotlNSFiV5rNfwEP4H//xvxT//SzK74WyueAeaNYPNlbir571FIgzF9aR8s/Kh49EtFoyy",
	"RSgAjrMdc6+KoPHrKVjHf82JoCRGs9wkkzPuS/52t6BT725QsCKcPA87Ghco9AAOHccVhLH/UQTp4Yog",
	"ecD+DqsghaGzZZBaqKMjRgbKQ9eqneY5DReWvUM0fJ1zFb+Mi6XbqRpKQVxP2/OicRx4LKDqA0c49ms+",
	"KD78Xt7hLGK6IuNio2bXqS38FITO/OwBaJ1u3w7EELm44JNhJZqbr1LoKK+nJ0X0fXXSG8pCTsp1Bkat",
	"lckdcPH4tvxDFAuejtE84Vm2HqNczsZIEkFxMi6SNgcWhrienlj/Rs24FzJZH+XS1r4xcMhI0jGiMRkj",
	"iRUeI7ZKwzWPXZWblmRO9zOizOSGD0u2ntMklEeN1dKGoKHr6cnfkB7mrGCxH9hQh/KGrFtDuG/I2oVx",
	"r02iCJXGgG4TtWG5aqrHgLD+tir2gBYoqmtxnREhqVSEqTGiLCYZYRqaz21/Z5yVPwXPRMRpwEVia+Wa",
	"PA2JMDrHt8gQL5riLIM0ypgKEin07uo9wlFEpC90e7ZEucQilHJfWQRwSCUyg9GMqFtCGErzRNEsAYvm",
	"wIq811PzaJrHXA4vkN9AvaIsUigmyhY3KsebCMeN6nFFlRjf4EqV8MnNJucsIoIdY0UWXASDm8pVzFgU",
	"lYPvsBS8R0OWSczATZaIq5HNbedSjNoYYWFPjgtHdkvX9xpC87i/+8H1tCW40B7AOpTnvCJCM0I3xCl8",
	"VM+0i67YDeO3/hEiLAhKcZaZ/KofPuib9YOfiXwsKGino/HoZyNEQ+iyYU1Gwj2MV1QagcRVUoB5BsZI",
	"241a7Ky9BWu/lOvXfqiCU/vRg672iwO29mcLe1+usSlvSGJf3K/g2zgMS91Nk7YiX5QptE8inqaExfU6",
	"L4GYz9ohL7lQVuIxv8xc6iEs26v6uiDRgo6qGw3ToqHljtAr8EEPcqESHC0t/FtQAJCL2EQCmTtv6v9V",
	"cqx/eTZ+Mj745N3UQIHljhyRpI/r2JVNRQuVgCiRS1KBwQtGMtU1FrZSiiPYCnydikuGlSJCQ/Dx48Vo",
	"vCHfSUq+AkgPn9j70+OAEMpi8iWU9hCTL454358ed0olAXtTtnp6aPIrQ6mcq6dF9qUr36nXqIV+XU9v",
	"NTO65DyR4TTR1fOuRZ4/xCK96aMunt9K1hrJm2SOnpM5EVCMzIqYLmW2ABgMZq53E6hcg+RwZ/A8EgTf",
	"xPw2EBe49PM9OzO3ioG+ubolfOQNFyYa3qQNDhv3M1XLnz0bUvs377nqnj6UQTQKwtYLSNuq4fvVWurr",
	"C1XrorOGfTruYsFzRWwuKRGeP6HJwdxCjsvO1q60IWeohAlB+ZMxIkzQaEliw41NpltcFMXJiDADd9FF",
	"rnUAEhMQs4tljtbHxZy7oawcP+W2O/OiSbU2ZK5cQe/+m2PQBhHp73c8BCootwvWbZvpbYsEQtMxtqDM",
	"9gi4pEdjtD/ZOTD/OpjsPDP/ejb58yU92q6ET5SIMzu3foI7Yu7t0T0+dsh6YIQHN3q5zoi8z0J6gp5F",
	"gjS7WRZsM7nxnhcQbU1eXZVZL2O0/+o1lusxOng1JTHN0zF68uonLOIxevrq5yVV5G3CK82gWreY5X2H",
	"F9rfwMtwfHYFFwDNcshqL6uJTnaefhzpfzzb+dH848XO/nPzr/2/7Dw5MP98cvDnSsXRtm1MIfzsEXdi",
	"FujfTGgPT3ae29+fP9vZP7D73T94sXPwzA4/ePZ82Ebf06i47Q+5zdkaJAmQDr2NWVAtkHY/5v+etgFc",
	"kLH/Wg9yiddS5EKVxr3t34FfMf+NPidYbtKvsB86Lu/LJxrI5FIrqndlefbrEKfLHizFX+D0zg9In6Q4",
	"SEzcWEbUwy7A+HdC5Y0cWMt6RRBWKCFYKsQZceZDGzi7iYxZETALycdhsniT/ce9emAtlBy6e0FBtBk7",
	"GrAYRUQEgg/OXk93CIt4TGJ0fIj0IDqnmojRLGdxYsqpr4gorNZlJvPluwv/g100zbVGlKwR+RIluaQr",
	"awCRNzS7TAKl+jd3wMBJZFjKWy6q/rbij4/SKAXWtfsI2qOZjb2tIcWgztl+qQRcZCTWyJIKUlFmBEmi",
	"QBsUOUE44WwBVZPMmUFyBdBsxNMZZWYmVznw6WRiiw/asvsvEZ27L6lE2HRQgAB4r/vuDc0kgFoBb2uG",
	"o5tbLGIJIgtW1ORfbv+1OinEgmuKqU1rJiNm5lwaetGAe/jQu7F4RIyQuEQBU7tBJ0Auks5YE99Lkgs6",
	"uv+J6xX1eeeSCOepfhyaqrEVvbC3rEfpn/Q9r9Z3aLrc1ipkvi9PC4sZTpJNHGRpHMiCSeNnSJr8C00A",
	"ReVjO38wRLKtSMLlkpS101w4+HFCNdG6j3qLIhTjNLhBDmlGuLe3VsyOKlM2JhCQQE37CqrQxU+HRu1T",
	"HM1ymsSVvtDNoor07eBpLR6vTjdZoBWj0EDa4c4mKqwOdie7k+0NMFkipbqXIHar5sGunNxalSXPaxUs",
	"9Fmp8NRspuL5cLq6DLdFWsZ+GeBwMazmjSgrTTaL4MmyMKOx5kFapIqWGzrKQsF7VSTb7IiO8iTUlJah",
	"nB1b11NfglP5hfPASfBRiNgr/W5C4Qtncux/JYjMExU2Dxejymo8nfJlelr/Qs8CPprefehREs2hBUQR",
	"gjjAht3mIqi0mLFugnLe6eiRbP53jU6pRzS5+lgBq7bRgje9AmlFiq/dLC3CUGshT7WwUI4GpE0vr3fR",
	"G8g+4mpJxC2VJPjsF7Lvay1Mxpv06XV3j0ojicauJ1UxZ3DFcFBa7eK1tgIiaZYEC0o1UYKRGz0MFV7G",
	"4ecBHYGLbicga3lhqWgPBcNV0X/8O9K0MihNswJMW554PfMcK8jL3frT9l+dSArBoYw30invBkUwXTcA",
	"BeR4PwoU4TTvk0CC9iMs3t5jt5mE/ahn0Zo6HQbkYY/DPocX4cJuTmUw3TFcVJRWw0n8gZX/nM/HSOYS",
	"4qDiwd3YTDS5D0BZ0aMiyXhyScGZK09bv4jV2laxTdB6Hyi7EXGmMGVOqW97HyvlNVj5IodqbABi3TKl",
	"WugisooKaCwOLPmDqWiKtgrfp01kLf6Li2yJmfkXoswEjtFZ0hIxyAWRZ0SYQq2Dar+C58v5dU3l1mEh",
	"eFGWH87nlAUDFF0mUtHkUK93eiIDOADlmjJb6lg/l9K04jdaZiFmDAApUPR0YD1shwCot4GL+pcuIPIO",
	"EYpdcrxPml5c1sbUGbd1zHTohye2Fg9btn1t3d6wCt0uOjcUkha2STqwCoD0sIcDRz9GAWBAerrkCRGY",
	"ReQ102JZR3yljZV4A9nPxWcgV5lPx8jUS0kxhfPSsg0knMsljvltnbzncHGlwkyhOaYJX/nKiyfxzKlI",
	"9dKhtAbzi4kj9h2xtbW2ZpRD9w0yp0EGMedJHKLIRoBGWYTSfLI5cUI18NNglD3spVHeuSwgXomXFkuS",
	"/Pj5+VOo077dutL7oCD7Jk+SSgEms4R+QEwLRLmWiqSbxsssvJrxsr2cOYilC9eNMFAXvmfdYX0d/Pr1",
	"LYWHBxx42fbMdYsOMeqyUVawm1r4EH7iUjXPoHf3m7QNCRBTHfiBloNNtPRzUP6Nmp61BmmdCQp1c7zi",
	"/vdFBGj77fzVWgNM/9Ai7v6ufLXVV/hf3HYQqiZ/mILuyOdFLexuWUGTXUoWOGR+bktt6LA0lMp+Y6EI",
	"a6HTavskRlvKquCMIxeqaQlj+3dtewiVzet/bRiRisQ/Xfc+72agE0GcvuW/7vpIb/WtWa4zIiCK2iRe",
	"5RUe3gaTv0GbyNotBblYyKLBB4rAHfVQctH70+NgwdTCGdvRcQZ62Epfx6lLHC3KJHSkb9cni27kVzJ0",
	"WEY8d43RZQZI4Uzmaavos1kSVLvlquOKVaxYSGA7DjOEkSCLPMFiCFUozdZtxfPSMtwpjMJLADGyRaS2",
	"685mw5W7eq/Agm0rnWrRNElcw2Q9yAQNeAtvwQzvubKDoaWb/ZPdiP3Dh8T99OEmeOz58NLZ16lX79Oo",
	"//DUQpJpSBBYESHBFZ83hIKim05ZbHOjTl3eZWkaBTxFs6GCe4+JU4ssX+g3eXRXAfkn7hX1fXpE3aE3",
	"VHUFk1rcmlK8iTi0JUiW4Mj1X9SIMb9sd+RePHrGxV0lKMbVLMHsJiRKhaWKIMflTnooBIqGEFGgphJr",
	"5pjrnUJrgokFnpBvXYkhFcp2+DRWLalEHqlcmBTkdKcAe8ekRNIVQQmdCQyNiBpux2YJGC/f7S5JUtW8",
	"W+IWCndPgubZ/YnabmAli8rA8qkHjU5X6nXy1n2rAcw4lA1mFIHjDHGLzg20tVQZ3pa8vyO5aENSECsN",
	"cGW3NOdRXb3NS9kWO9wKu2iB7bpiD8xxbOCv1gi7ZUDZ4bplgN/fum1ICXLLCJMIuUHHmKBEEmoR/X29",
	"la1FtRu+QVfke5Ma2RtVR/ScpZvVwr5zjemTh68OHXLjbYo5PflmdSVL7+Zm1ZuHjG6rfNRfgLn0IJna",
	"5H4x4qqNJyBzDqm4fBYqtTwMxwPLKJ8F6ie3VUhuKQVVfxZN3SU3PoDHNuDCSOkrg+xdw76ayB7dhQok",
	"f2rJUqpnMzWYHIjRMOpoUKjZ5VFJHooOLY+9So+HlKh2xajtxEPi2C3o5RKfOvK1HgUL8IPt0PNwqGgJ",
	"9IfFXIKwXbQHTW7BcWWXnzoTPALJ8S1tUIvuR+XPfvBPthA4JueVagEhCdz+TmL04QLZr1zIFfKaLIFT",
	"CcKyjZnUDgXbGkb+sP6axBYroQZODidfTY8vwImiCvqlH0obPVgk4SATtnp4djryYltHq31AakYYzujo",
	"5ejJ7mT3Caiqagl43TMBsi9/Gy2Mk9+6szi0jBq9JQomtgIrSJVgQ4CPDyYTK6QoO4lXkmPvX6XBs5Gc",
	"++RqfxnYcygqVxahjM/M0nXJViuoOEGSiBURVjaGzAN36/SOTFCwN1lm3VrVvV/YvU95TEbm3IhURzxe",
	"P+ym9fzOEFCLaNea6dfvh3QNGYqWmC1IrPH0NIx0KIeHhNuCHvciIDByNk+oueV3Pr1jAMYeIBRu0r/v",
	"1esJtdKyP+4x8Vp+WTG8BXDsLPj+FkzWT2HmgvZ690AaLBGqpVT4YBFnyDXx23OFPL06tB5Om0l6DSy/",
	"Axmh2XIJRBcscEpMfaFfWkounly8q5RdtI2MygKj6BX6wesd8MPH0fYu+pBSZUvl5oJVKtJCNUy9wK85",
	"ATODEcVGs/XrYhnNhYuzbdZ0rPPxT49IPT0dzQJE5BIBKmqFa6UlzZV8Gqo0igrFHIlmvWIIAb83t3U9",
	"gkzqdhjEeny8B5at8d1CmXu/FS3Avm5GpY1KzkOpNFDY+erq9MTRmH5aSxLzG5RV+bpPbw0p4Y+b8X1v",
	"hqEIyK37xpcAI5mRiM5pFCJ9ufdbedhf92oesLZnL9DyrofGq03uwm3sEBdoQRgxMQIuLPb0pE6WO/jJ",
	"/C+zg2g/fkp+fDHZPzCJ8oHLUikh3X5bSkfE/95yIH38GP/5/7gFf5nsvMA780+/7T//uv0vo+9No5vS",
	"J5SIB3dFmCM2+E+vbOYxCKse3utJAJd8UTLR3RGtlJbw3Ou2uD0HkDNbe6Rm74apju4s5xr2gDSveHZc",
	"DGyc/9OQwFrUuZeKZxm5HxfQAPiF3L+O2++rg/Px1a76UiESdUMeSv2KAhO2qGAKC1U9tYdXwnwUCLWR",
	"JnbwHc7BulzAWnB/nayY0vWsogxlgi8g/PB+5I6hPYUL/fUpX1/aOdcCWplu4W5tPSWCZ8Yl6jSVGWHR",
	"MsXiZhcdGpB3PIaVM1OPE7ypYlU239I8dYYl0QJPkzG8KYF5xDMuV2k/5CO3PeTcZFBZGqr/GvnNGJpg",
	"511cvMCTH2p7L9Ub4Cnn9RhYXXYypRVsfFEBvnFZgmqbEbGTYSoKUtPqKaamxEWDHTbw9oj8cMgZOR9o",
	"ScIFI6tg7IwnSWhQye0a+T9CSYTlmkUlnjXRa8GQM6Kf3ZQLr4g2NEKXu8irXeLMkhmWEug/oeZLW+AC",
	"0bm+HivbZreobkAZwgwRLBJKhOMcoeuChardl4fnyZVj+G5MebMLO5Qpe43oxq6VBFS/05cORCu4GgnV",
	"ahv5EhESu1kDLPyQmcScyn13zPwh7r1h5N61r3LvvXpj/zBt26ZC0ua71Nv8a549Jxiy0UzellOCqn3/",
	"a4SPNEuPEZROYTHEiYIhHVLkXMgnxGQgxTOe8MUaxUTQlQsqhggyLm4SOlc79omCu+CaNKL3vCir4R0c",
	"AOwIsXlJzrj07kilGb8pXf0Ydybc8/8RLMqD4mSq0ARCZJps1UMRZBLqI269TScFJTyMkm4J1Ny9Ck03",
	"CL5WJyoPkPu17RAji6RNF+i5omoN5FkU+4EaMJIItMRW1LGnVRBeJuiKJmRhTQTek1KQnURb5d2Afgsp",
	"ZnhBUuhLcD0tnesQYAs+vCiB/9reRdd+FSPOkjUEk9TpXSNa4lWQ4HOP3v1CWo9D6qFur4PpvEZ13iYN",
	"f9aHg6HDmj0GD/0aDQuB2YZ8XjP1nAmCoyUUcnBhwzDFk43Q0hIwVgQzjiiT+XxOI1MCqEFBY5RSKSlb",
	"vES/FHdo99CmnlxAeHw1jG63aKSzewxNuT4F4/7MrGfFQhWofhm1rDWqB8Y2VqtEqPZX+Q54T2sPZq6W",
	"+lgstcs8Mi8sdNWCe5jg6EaGjv9eDAbu2LrkB/7lYrFmeIBCzpocp7jZHQ+sk7rLscNeOFthzr6V9hnV",
	"ABU8UOuERXOA6vP5/vDQdcYpA+TlHR/NiqR/Um75sSXMcinvzfwmb2Sxsi1IMOCRdO5CjyTu7RrEK0wT",
	"4Ev+rDUaBHlr7zeGU/K1S2M3aqJ5yEqZtGbZhkfWtnDeRZeGRN2bpnFMWU5K7yR12edG6NNkJBVNEoQh",
	"FLpPp9eiSJ/BW48xaWJYOjhL6wGI9oU1JWi7ttFaw308n+6puNQzOKh439ZrsIjldSG6RQjupwG18ZtE",
	"eGZkJDvHICOEcKk9Tr0pzcZ7hboyp4zK5T3trNZOgZF+jhJipcgaNYu8EigQZqWUxXRF4xwnvnalnMS1",
	"i1zTwmRt01BMUlDmaKmHx53nbKhLHAxb/tQtfruCDDajvEfgbYVefJ6zTRhbhWQegLnV5wsQAnTZ7fId",
	"nMDfKwfX6yTOGWrzCfe4t3pTDgMHGHJh5vqxNoHtvXZiA22rNzRnD6RlGUwiXD2WxqlI13q/28BoVLYY",
	"DGtUKho5F2rVTPCD9JczKQ+7yKXSExZnnBpznqsjqXjRRbOsQq9oWnQrIEMslXL4o6M4WhBV20j/Hb/P",
	"a/PwNlPbHrd5ty+XgueLZZb7O2wlyqnRJJDbJypweG/PkwoDoqmvrEsZ9MppXvLWDBnGsW0ZSyvkoK0I",
	"S7JDmSRMUsjfkvnMnI4J9NpujcTo5efjJl0VCZtoa38HOhaZ1OkwPS2q8xeJ+vvjsknUfijItz1+2G7f",
	"mHEWpGNpW8krsPzBBLrX2vVtQmI7NI9J4nD0Q0P5LCn1Md15vcHwA0jySeKtHvapGq0aNvRYDtVyhY2s",
	"kPsPe1yhIzIdkm1v8aHuU1c9iFYPTq6Zwl+27yesAiQII0Zuzcn53GigYOLOspMtmZ3fUSTpf02etnaj",
	"LkWQ+0oNFj/tcRPfHhENDngBQTKUJLGN4jWdWotovTH6CEu9xDL6ONLaUBEn9VLPNC5/3N5F15beYDow",
	"weKUjJFfJnHswmGMUVdz07EtKDO2NVp2q3ngbjksI7tvWFnrguRLlkA3XLPvEMuWHDr6B7SB3rLMUq3B",
	"QqkF3FH3qzUHNXFhq/V/y4cLtnOnd+v7Pk5dD5O7ieBiN2RpY8qftl/ch4t9NC39Z2t0emIWp0o6ADIt",
	"+zQvsymP8J0Y28O/iN52vlOmR8+LmAOAD/giPjphGZT6b6ZNSe8PAywTuB8zkuTUgdMeO3A9lbYFv7Wn",
	"/5oTUx4teAiHZYiWMb5B0UGw7bVhvAACsP4w4QA8QwWqEWGKCpKsu57lOiZ6LvTp3LaCocxU8CgaZFyf",
	"nPwNpURhiJDd+rvNc/v7GP09jZ/9fduURrCVNHb9gBf48hZLxIjemJuxLfzdrnwdxzfhB8aWMGs0Rf/0",
	"fQmqPO4HCtWkgQk7QjVrN+tujDQQFFXtkuCs8LUM0apbflP38Xi0Sk9juYlE00hy1d+PK4CE0zm/XQTT",
	"cJp5yLDSkgwfPhDJowQtJBZZawWlNuIzguTqAjQKUP9pgxbs020c2VLO8yRZt57gEY5Rjezv7tC2KAy6",
	"tG2lYvsg105opflqR75KcSiaAT9+zGetL1TgjjiLM9Q+clXRii8ajZxswTt4dBQWux/ZqS14qP+S4ehG",
	"qzpL/RxB8y7Cim/HCKOnk6fIbRaid23c7+5H1vrQ6z08oMgOgHosPw8c1FlePajOa5PmiaIZFmpPa387",
	"0JOgw505p6GSpQ6htktW4SiZUYbh+e7OtodJ78aRvyWxXQEpePe58zZvknb9dP9JqCB4QmyYqUTPn06P",
	"TOTpPYVz2ELlvCwPsGEn3dffDdpUUiw6fp0WrvviIm0d25Z8CXH51SzHiRcJY+7gdptQqD86NJNvJhS2",
	"ZXOWKyteL2xIpVFtfpABO3EYPhhvcucezw/EGfkwh6PoFjvcCerN92vG3vhP7ZkvfthSh8bjkKq5YRHa",
	"8lBJS1UYNEmH0+Sb3qNGvvGjvmmN1YY6L5o5f/Jh/BItE4fFs0tBFwsi/FzKMn/occSz5lrfKeugcXRF",
	"h/bOnDBlUEbivxbNTQdmh3pPyJ2P2R5Y5ZRTogSNZCP1qz99vz9Zvzf+4nES8z99yysblERbkn+/RQ67",
	"n5rezAyGN1VrH9C10Rx953kXOe2bsc0/yjT8Uabhd1umoY/UK+UbNmJ4x0UvtN8d1f9RLOI7F4sYfD8e",
	"vXCDD1ntmrhlwdHRcn28psxtF+O6aLH8eCq61+065LWxraG9rIjWGnOrlrF7tjZ96y6nQ+PMZuvKU2Pb",
	"JYM6CS+y1oGLHN9yZKU2/Ih8yfYf/on5Izjij+CI7x4c0dEGo0MLLsIjBvjCvVt677o35fJWnoZLrh9z",
	"yBErD90xkT0zYodnvcUPr6fS8IwP2aMXQLyeVpbqQrnlY24D90VhDC0wIuXMZmZetMJJbkW3wmWk0Vc2",
	"2mhH2zsz5lHRZdYYQprFBi3o99bqkqQ+pxYIckkQjgSXMoSwvd/g/wcEJ8LG3iZ8hpOk16B7CfWuZiQx",
	"elDKV8TKC6BWyrAkaJpGdAmB92ps8qjsKYCkTiIA5LiYkYVDax+rMjh9mDh6G4xppqwcTl84FwA/QLKp",
	"UEHKYzpff8eDf6xoMIeNzQPCQiRR4Nsr3+Z7hNGWPaXCX4wVT2mkyWd7M4d/QM/44NWm0WuUqsUW47aC",
	"sEQpjsn9wqWnQAyWOMDMpCUTuaQZ2sJxvGdZhiOePSDP66ncLvnXbz2KN/Qb6CTPeie3+JFCqh9LBnLJ",
	"xgHNprqzuOyTFvY5V4c/nBXGRariGc8VwmiV9vKW73psjxAr0tEs7K6M4nq6WazI0Mt/PX3YkE5TrKR0",
	"kHsXd6/aW7dN8jgHNnA9fSN4WglJqxHI7/zWNhtG3T+GNBgQqnl3swWsiU3pz/NuYwPILmId8QVcd6YP",
	"c6yNnuh6015UmF2nQjYD6+ReTzcokVsDwxg/Hy2/5iHJKtQKM0RYVTtjz2Pwngdq2AIZ+K18HtK+OBME",
	"38T8tmFp1OvApzCXObtcJKOXoz2c0b3V/ujrp6//PwAA///jBCvpjQoBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
