name: Notify planner repo
on:
  push:
    branches:
      - main
      - stable

jobs:
  notify:
    uses: kubev2v/migration-planner-workflows/.github/workflows/repo-dispatch-notify.yml@main
    with:
      event-type: agent_repo_updated
    secrets:
      APP_ID: ${{ secrets.MIGRATION_PLANNER_SYNC_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.MIGRATION_PLANNER_SYNC_APP_PRIVATE_KEY }}
